---
name: Emoncms
version: 0.6.1
slug: emoncms
description:
  Emoncms is a powerful open-source web-app for processing, logging and
  visualising energy, temperature and other environmental data.
url: https://github.com/inverse/hassio-addon-emoncms
ingress: true
startup: system
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
services:
  - mysql:need
  - mqtt:want
map:
  - ssl
ports:
  80/tcp: null
ports_description:
  80/tcp: Web interface (Not required for Ingress)
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
  certfile: str
  keyfile: str
  remote_mysql_host: str?
  remote_mysql_database: str?
  remote_mysql_username: str?
  remote_mysql_password: password?
  remote_mysql_port: port?
  mqtt_basetopic: str?
  remote_mqtt_host: str?
  remote_mqtt_username: str?
  remote_mqtt_password: password?
# image: inversechi/hassio-emoncms-{arch}
